from .article_heuristics import HeuristicsArticleNavigationPage
from .product_navigation_heuristics import HeuristicsProductNavigationPage
from .search_request_template import DefaultSearchRequestTemplatePage
