from setuptools import find_packages, setup

setup(
    name="zyte-spider-templates",
    version="0.9.0",
    description="Spider templates for automatic crawlers.",
    long_description=open("README.rst").read(),
    long_description_content_type="text/x-rst",
    author="Zyte Group Ltd",
    author_email="info@zyte.com",
    url="https://github.com/zytedata/zyte-spider-templates",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "extruct @ git+https://github.com/Gallaecio/extruct.git@query-input",
        "form2request",
        # "formasaurus>=0.9.0",
        "formasaurus @ git+https://github.com/Gallaecio/Formasaurus.git@form2request",
        "jmespath",
        "pydantic>=2",
        "pydantic>=2.1",
        "requests>=0.10.1",
        "scrapy>=2.11.0",
        "scrapy-poet>=0.24.0",
        "scrapy-spider-metadata>=0.2.0",
        "scrapy-zyte-api[provider]>=0.23.0",
        "web-poet @ git+https://github.com/scrapinghub/web-poet.git@73c4dfa557311e8e767d9db71246f16e41dd3e93",
        "zyte-common-items>=0.23.0",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: BSD License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
    ],
)
