import pytest

from zyte_spider_templates.heuristics import article_filter, product_filter


@pytest.mark.parametrize(
    "content_filter,test_input,expected",
    [
        (product_filter, "", True),
        (product_filter, "https://example.com", True),
        (product_filter, "https://example.com/search", False),
        (product_filter, "https://example.com/search.php", False),
        (product_filter, "https://example.com/articles", False),
        (product_filter, "https://example.com/articles.cgi", False),
        (product_filter, "https://example.com/articles#fragment-here", False),
        (product_filter, "https://example.com/xyz123/articles?q=1", False),
        (product_filter, "https://example.com/xyz123/articles/x?q=1", True),
        # Regex
        (product_filter, "https://example.com/signin", False),
        (product_filter, "https://example.com/signin.html", False),
        (product_filter, "https://example.com/sign-in", False),
        (product_filter, "https://example.com/sign_in", False),
        (product_filter, "https://example.com/login", False),
        (product_filter, "https://example.com/login.html", False),
        (product_filter, "https://example.com/log-in", False),
        (product_filter, "https://example.com/log_in", False),
        (product_filter, "https://example.com/logout", False),
        (product_filter, "https://example.com/logout.html", False),
        (product_filter, "https://example.com/log-out", False),
        (product_filter, "https://example.com/log_out", False),
        (product_filter, "https://example.com/contact-us", False),
        (product_filter, "https://example.com/contact_us", False),
        (product_filter, "https://example.com/contactus", False),
        (product_filter, "https://example.com/contactus.asp", False),
        (product_filter, "https://example.com/contact", False),
        (product_filter, "https://example.com/contact.html", False),
        (product_filter, "https://example.com/lost_password", False),
        (product_filter, "https://example.com/lost-password", False),
        (product_filter, "https://example.com/forgot_password", False),
        (product_filter, "https://example.com/forgot-password", False),
        (product_filter, "https://example.com/forgot-password.cgi", False),
        (product_filter, "https://example.com/terms-of-use", False),
        (product_filter, "https://example.com/terms-of-use.html", False),
        (product_filter, "https://example.com/terms-of-service", False),
        (product_filter, "https://example.com/terms-of-conditions", False),
        (product_filter, "https://example.com/terms_of_use", False),
        (product_filter, "https://example.com/terms_of_service", False),
        (product_filter, "https://example.com/terms_of_conditions", False),
        (article_filter, "", True),
        (article_filter, "https://example.com", True),
        (article_filter, "https://example.com/search", True),
        (article_filter, "https://example.com/search.php", True),
        (article_filter, "https://example.com/articles", True),
        (article_filter, "https://example.com/articles.cgi", True),
        (article_filter, "https://example.com/articles#fragment-here", True),
        (article_filter, "https://example.com/xyz123/articles?q=1", True),
        (article_filter, "https://example.com/xyz123/articles/x?q=1", True),
        # Regex
        (article_filter, "https://example.com/signin", False),
        (article_filter, "https://example.com/signin.html", False),
        (article_filter, "https://example.com/sign-in", False),
        (article_filter, "https://example.com/sign_in", False),
        (article_filter, "https://example.com/login", False),
        (article_filter, "https://example.com/login.html", False),
        (article_filter, "https://example.com/log-in", False),
        (article_filter, "https://example.com/log_in", False),
        (article_filter, "https://example.com/logout", False),
        (article_filter, "https://example.com/logout.html", False),
        (article_filter, "https://example.com/log-out", False),
        (article_filter, "https://example.com/log_out", False),
        (article_filter, "https://example.com/contact-us", False),
        (article_filter, "https://example.com/contact_us", False),
        (article_filter, "https://example.com/contactus", False),
        (article_filter, "https://example.com/contactus.asp", False),
        (article_filter, "https://example.com/contact", False),
        (article_filter, "https://example.com/contact.html", False),
        (article_filter, "https://example.com/lost_password", False),
        (article_filter, "https://example.com/lost-password", False),
        (article_filter, "https://example.com/forgot_password", False),
        (article_filter, "https://example.com/forgot-password", False),
        (article_filter, "https://example.com/forgot-password.cgi", False),
        (article_filter, "https://example.com/terms-of-use", False),
        (article_filter, "https://example.com/terms-of-use.html", False),
        (article_filter, "https://example.com/terms-of-service", False),
        (article_filter, "https://example.com/terms-of-conditions", False),
        (article_filter, "https://example.com/terms_of_use", False),
        (article_filter, "https://example.com/terms_of_service", False),
        (article_filter, "https://example.com/terms_of_conditions", False),
    ],
)
def test_might_be_relevant_content(content_filter, test_input, expected):
    assert content_filter.might_be_relevant_content(test_input) == expected
